version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT:-8080}:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=neon
      - SPRING_DATASOURCE_URL=${NEON_DATABASE_URL}
      - SPRING_DATASOURCE_USERNAME=${NEON_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${NEON_PASSWORD}
    networks:
      - pets-network

networks:
  pets-network:
    driver: bridge
